version: '3.8'
services:
  react-query-app:
    container_name: react-app-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - 4000:3000
